logging:
    level:
        org:
            mrpaulwoods: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        name: bookmarks
        password: bookmarks
        url: jdbc:mysql://localhost:3306/bookmarks
        username: bookmarks
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    github-client-1:
                        client-id: ${bookmarks-client-id}
                        client-name: Github User
                        client-secret: ${bookmarks-client-secret}
                        provider: github
                        redirect-uri-template: http://localhost:8080/login/oauth2/code/github
                        scope: user
